[package]
name = "takumi_py"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[lib]
name = "_core"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
image = { version = "0.25", default-features = false }
pyo3 = { version = "0.28.2", default-features = false, features = ["extension-module", "abi3-py310"] }
serde-pyobject = "0.8.0"
takumi = { version = "1.7.0", path = "takumilib/takumi" }
