[package]
name = "takumi_py"
version = "0.3.0"
edition = "2024"
license = "GPL-3.0-or-later"

[lib]
name = "_core"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
image = { version = "0.25", default-features = false }
parley = { version = "0.11", default-features = false, features = ["std"] }
pyo3 = { version = "0.28.2", default-features = false, features = ["extension-module", "abi3-py310"] }
serde = { version = "1.0.228", features = ["derive"] }
serde-pyobject = "0.8.0"
takumi = { version = "2.5.4", path = "takumilib/takumi", features = ["from-html", "svg-backend"] }
takumi-core = { version = "0.11.0", path = "takumilib/takumi-core" }

[lints.clippy]
redundant_closure_for_method_calls = "deny"

[lints.clippy.all]
level = "deny"
priority = -1
