from collections.abc import Sequence
from typing import Any

class TakumiError(Exception): ...
class HtmlParseError(TakumiError): ...
class NodeValidationError(TakumiError): ...
class NodeDecodeError(TakumiError): ...
class StyleSheetError(TakumiError): ...
class RenderError(TakumiError): ...
class UnsupportedFormatError(TakumiError): ...
class CompiledNode: ...
class CompiledStyleSheet: ...

class NativeRenderer:
    def __init__(self) -> None: ...
    def compile_node_py(self, node: Any) -> CompiledNode: ...
    def compile_node_msgpack(self, packed: bytes) -> CompiledNode: ...
    def compile_stylesheet(self, css: str) -> CompiledStyleSheet: ...
    def compile_stylesheet_lossy(self, css: str) -> CompiledStyleSheet: ...
    def render_compiled(
        self,
        node: CompiledNode,
        *,
        stylesheets: Sequence[CompiledStyleSheet] | None = None,
        width: int = 1200,
        height: int = 630,
        format: str = "png",
        quality: int | None = None,
    ) -> bytes: ...
